#!/usr/bin/env node
/**
 * [COMPANY] Sitemap Generator
 * Auto-discovers every HTML page in the repo and its .md mirror.
 * Outputs sitemap.xml with both HTML and .md URLs for every page.
 *
 * Usage:
 *   node build-sitemap.js
 *
 * Called automatically by:
 *   - build.js  (after full or single-page build)
 *   - mirrors.js (after generating static mirrors)
 *
 * Adding a new page:
 *   Just create the HTML file. Run build.js or mirrors.js.
 *   The sitemap updates automatically on the next run.
 */

'use strict';
const fs   = require('fs');
const path = require('path');
const ROOT = __dirname;

const DOMAIN  = 'https://www.[DOMAIN]';
const TODAY   = new Date().toISOString().slice(0, 10);

// Directories to skip entirely
const SKIP_DIRS = new Set(['source', 'partials', '.git', 'node_modules', 'status', 'reference', 'planning', 'wizard', 'assets', 'css', 'js', 'data', 'builds', 'templates']);

// Files to skip
const SKIP_FILES = new Set(['404.html']);

// Priority rules — checked in order, first match wins
const PRIORITY_RULES = [
  [p => p === '/',                                               '1.0', 'weekly' ],
  [p => /book-now/.test(p),                                     '0.9', 'monthly'],
  [p => /services\/(in-home-primary-care|iv-therapy|botox|weight-loss|urgent-care)/.test(p), '0.9', 'monthly'],
  [p => /services\//.test(p),                                   '0.8', 'monthly'],
  [p => /about\/?$/.test(p),                                    '0.8', 'monthly'],
  [p => /[SERVICE NAME]/.test(p),                                   '0.8', 'monthly'],
  [p => /locations\//.test(p),                                  '0.8', 'monthly'],
  [p => /gabby/.test(p),                                        '0.7', 'monthly'],
  [p => /pricing|faqs|savings|[SERVICE NAME]/.test(p),              '0.7', 'monthly'],
  [p => /contact|service-area/.test(p),                         '0.6', 'monthly'],
  [p => /privacy/.test(p),                                      '0.3', 'yearly' ],
];

function getAttrs(urlPath) {
  for (const [test, priority, changefreq] of PRIORITY_RULES) {
    if (test(urlPath)) return { priority, changefreq };
  }
  return { priority: '0.6', changefreq: 'monthly' };
}

// Convert a file path (relative to ROOT) to a URL path
function toUrlPath(filePath) {
  // Normalise separators
  let p = filePath.replace(/\\/g, '/').replace(/^\.\//, '');
  // index.html at root → /
  if (p === 'index.html') return '/';
  // dir/index.html → /dir/
  if (p.endsWith('/index.html')) return '/' + p.replace('/index.html', '/');
  // strip leading dot if any
  return '/' + p;
}

// Walk the repo and collect all .html files
function collectHtml(dir) {
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name)) {
        results.push(...collectHtml(path.join(dir, entry.name)));
      }
    } else if (entry.isFile() && entry.name.endsWith('.html') && !SKIP_FILES.has(entry.name)) {
      results.push(path.join(dir, entry.name));
    }
  }
  return results;
}

function urlEntry(urlPath, { priority, changefreq }, isMd = false) {
  const loc = DOMAIN + urlPath;
  const mdNote = isMd ? '\n    <!-- machine-readable markdown mirror -->' : '';
  return `  <url>${mdNote}
    <loc>${loc}</loc>
    <lastmod>${TODAY}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${isMd ? (parseFloat(priority) - 0.1).toFixed(1) : priority}</priority>
  </url>`;
}

function build() {
  const htmlFiles = collectHtml(ROOT);
  // Sort: root first, then core pages, then services, then locations
  htmlFiles.sort((a, b) => a.localeCompare(b));

  const entries = [];
  const seen = new Set();

  for (const absPath of htmlFiles) {
    const rel     = path.relative(ROOT, absPath);
    const urlPath = toUrlPath(rel);
    const mdRel   = rel.replace(/\.html$/, '.md');
    const mdPath  = path.join(ROOT, mdRel);
    const mdUrl   = toUrlPath(mdRel);
    const attrs   = getAttrs(urlPath);

    if (seen.has(urlPath)) continue;
    seen.add(urlPath);

    entries.push(urlEntry(urlPath, attrs, false));

    // Add .md entry if the mirror exists
    if (fs.existsSync(mdPath)) {
      entries.push(urlEntry(mdUrl, attrs, true));
    }

    // For directory index pages, also add flat .md alias (e.g. /about.md, /gabby.md)
    const flatMdRel  = rel.replace(/\/index\.html$/, '.md').replace(/^index\.html$/, 'index.md');
    const flatMdPath = path.join(ROOT, flatMdRel);
    const flatMdUrl  = toUrlPath(flatMdRel);
    if (flatMdRel !== mdRel && fs.existsSync(flatMdPath) && !seen.has(flatMdUrl)) {
      seen.add(flatMdUrl);
      entries.push(urlEntry(flatMdUrl, attrs, true));
    }
  }

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  [COMPANY] Sitemap — auto-generated by build-sitemap.js
  Generated: ${TODAY}
  Both HTML pages and their .md markdown mirrors are listed.
  Markdown mirrors allow AI crawlers and LLMs to parse content efficiently.
  Do not edit manually — re-run: node build-sitemap.js
-->
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml">

${entries.join('\n\n')}

</urlset>`;

  fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), xml, 'utf8');
  console.log(`Sitemap: ${entries.length} URLs (${htmlFiles.length} HTML pages + mirrors)`);
}

build();
module.exports = build;
