#!/usr/bin/env node
/**
 * [COMPANY] Alternate Link Patcher
 * Injects <link rel="alternate" type="text/markdown" href="..."> into every
 * static HTML page that has a corresponding .md mirror.
 *
 * - Idempotent: checks for existing tag before inserting
 * - Only patches static HTML files (not files generated by build.js — those
 *   get the tag directly in their template)
 * - Called automatically by mirrors.js after generating mirrors
 *
 * Usage:
 *   node patch-links.js
 */

'use strict';
const fs   = require('fs');
const path = require('path');
const ROOT = __dirname;

// Files generated by build.js — these get the alternate link in their template,
// do not patch them here (would double-insert on next build)
const BUILD_JS_SLUGS = JSON.parse(
  fs.readFileSync(path.join(ROOT, 'build-manifest.json'), 'utf8')
).pages.map(p => path.join('services', p.slug + '.html'));

const SKIP_DIRS  = new Set(['source', 'partials', '.git', 'node_modules', 'status', 'reference', 'planning', 'wizard', 'assets', 'css', 'js', 'data', 'builds', 'templates']);
const SKIP_FILES = new Set(['404.html', ...BUILD_JS_SLUGS]);

function walk(dir) {
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory() && !SKIP_DIRS.has(entry.name)) {
      results.push(...walk(path.join(dir, entry.name)));
    } else if (entry.isFile() && entry.name.endsWith('.html')) {
      const rel = path.relative(ROOT, path.join(dir, entry.name));
      if (!SKIP_FILES.has(rel)) results.push(path.join(dir, entry.name));
    }
  }
  return results;
}

// Derive the public .md URL for a given HTML file path
function mdUrl(absHtmlPath) {
  const rel = path.relative(ROOT, absHtmlPath);
  if (rel === 'index.html') return '/index.md';
  // dir/index.html → /dir.md (flat alias) and /dir/index.md
  // Use the flat alias as the canonical alternate (shorter, cleaner)
  if (rel.endsWith('/index.html')) {
    return '/' + rel.replace('/index.html', '.md');
  }
  return '/' + rel.replace(/\.html$/, '.md');
}

// Check if the .md file actually exists on disk
function mdExists(absHtmlPath) {
  const rel    = path.relative(ROOT, absHtmlPath);
  // Prefer flat alias for directory index files
  if (rel.endsWith('/index.html')) {
    const flat = path.join(ROOT, rel.replace('/index.html', '.md'));
    const deep = path.join(ROOT, rel.replace('/index.html', '/index.md'));
    return fs.existsSync(flat) || fs.existsSync(deep);
  }
  return fs.existsSync(path.join(ROOT, rel.replace(/\.html$/, '.md')));
}

function patch(absHtmlPath) {
  if (!mdExists(absHtmlPath)) return 'skip-no-md';

  const url  = mdUrl(absHtmlPath);
  const tag  = `<link rel="alternate" type="text/markdown" href="${url}">`;
  let   html = fs.readFileSync(absHtmlPath, 'utf8');

  // Already patched?
  if (html.includes('rel="alternate" type="text/markdown"')) return 'already-done';

  // Insert after <meta name="robots" ...> if present, else after last <meta> in <head>
  // Fallback: insert just before </head>
  let patched = html;
  const robotsMatch = html.match(/<meta name="robots"[^>]*>/);
  if (robotsMatch) {
    patched = html.replace(robotsMatch[0], robotsMatch[0] + '\n  ' + tag);
  } else {
    patched = html.replace('</head>', '  ' + tag + '\n</head>');
  }

  if (patched === html) return 'no-change';
  fs.writeFileSync(absHtmlPath, patched, 'utf8');
  return 'patched';
}

function run() {
  const files = walk(ROOT);
  let patched = 0, skipped = 0, already = 0;

  for (const f of files) {
    const result = patch(f);
    const rel    = path.relative(ROOT, f);
    if (result === 'patched')      { patched++; console.log(`  ✅ patched: ${rel}`); }
    else if (result === 'already-done') { already++; }
    else if (result === 'skip-no-md')   { skipped++; }
  }

  console.log(`\nAlternate links: ${patched} patched, ${already} already done, ${skipped} skipped (no .md)`);
}

run();
module.exports = run;
